require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "fixtures/dummy/node_modules/**/*"
    - "fixtures/dummy/vendor/**/*"
    - "fixtures/external/**/*"

Layout/LineLength:
  Max: 100
  Exclude:
    - "test/**/*"

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

Style/CaseEquality:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
